# Generated by Django 5.0.2 on 2024-02-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_index', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('major', models.CharField(default='Computer Science', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('batch', models.CharField(max_length=255)),
                ('phn_no', models.IntegerField()),
                ('pronouns', models.CharField(max_length=255)),
                ('research_interests', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_current_user', to='Bumble4Stem.users')),
                ('r2id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_user', to='Bumble4Stem.users')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_current_user', to='Bumble4Stem.users')),
                ('m2id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to='Bumble4Stem.users')),
            ],
        ),
    ]
