# Generated by Django 4.0.3 on 2024-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bumble4Stem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar_index',
            field=models.IntegerField(default=0),
        ),
    ]
