# Generated by Django 4.0.3 on 2024-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bumble4Stem', '0002_users_avatar_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='major',
            field=models.CharField(default='Computer Science', max_length=255),
        ),
    ]
