# Generated by Django 4.0.3 on 2024-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bumble4Stem', '0004_remove_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='bio',
        ),
        migrations.AddField(
            model_name='users',
            name='Q1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Q2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Q3',
            field=models.TextField(default='', max_length=100),
        ),
    ]
